POST http://localhost:8080/upload
X-Auth-Token: c184a35f-54fd-4772-a81a-155fbf741083
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="application"; filename="application.xml"

< D:/dev/base-framework/business/app/src/main/resources/application.yaml
--WebAppBoundary--

###
GET http://localhost:8080/login/validateCode?base64

### login
POST http://localhost:8080/login/process
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: 0243dc3c-058d-4b2c-84a1-7dd082dec69c

username=admin&password=admin&validateCode=725s

###
GET http://localhost:8080/upload/down/application.xml
X-Auth-Token: 98da02ae-6216-4223-8353-b107b8335b72


### permission test
GET http://localhost:8080/admin/
Content-Type: application/json
X-Auth-Token: 4794fe92-9724-4e90-afe9-d6ff00be8520


### useradd
POST http://localhost:8080/user/addUser
Content-Type: application/json
X-Auth-Token: 01877fb8-9d12-47a4-88fc-105b658f6bbf

{
    "username": "admin5",
    "phone": "13800013800",
    "email": "admin3@admin.com",
    "displayName": "admin 3",
    "enabled": true
}


### updatepassword
POST http://localhost:8080/user/updatePassword
Content-Type: application/json
X-Auth-Token: 268aa250-d2dd-4f40-ae94-8beed84eebaf

{
    "validCode": "admin5",
    "username": "admin5",
    "oldPassword": "13800013800",
    "password": "admin3@admin.com"
}

### userinfo
POST http://localhost:8080/user
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: 6143dd1d-50a8-4bc8-9233-b88fe793c525


### userinfo by open api
POST http://localhost:8080/_api/user/
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: 70b1e491-2ffc-4932-8ceb-9c4d37e68267

username=admin



### userinfo by open api
GET http://localhost:8080/_api/_status
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: 70b1e491-2ffc-4932-8ceb-9c4d37e68267

