server:
  port: 8080

logging:
  level:
    p6spy: info
  file:
    name: @project.artifactId@
    path: ./log
sentry:
  dsn: http://c6715a73355a45ec948d9e0e668c0233@10.168.2.142:9000/2
  sentry-client-name: @project.artifactId@

spring:
  application:
    name: @project.artifactId@
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource:
    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.168.2.142:3306/app?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name : com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://10.168.2.142:3306/app?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
      username: ENC(W/weR/Um/pwb9TnIi1IzDxVNGgcMX0wPqqDMC2WqE3WDuvJ6oAD04qlHsQCNuUeU)
      password: ENC(W/weR/Um/pwb9TnIi1IzDxVNGgcMX0wPqqDMC2WqE3WDuvJ6oAD04qlHsQCNuUeU)
      filter:
        slf4j:
          enabled: false

  flyway:
    enabled: false
    url: ${spring.datasource.druid.url}
    password: ${spring.datasource.druid.password}
    user: ${spring.datasource.druid.username}
jasypt :
  encryptor :
    password : 11112222

xxx: ENC(W/weR/Um/pwb9TnIi1IzDxVNGgcMX0wPqqDMC2WqE3WDuvJ6oAD04qlHsQCNuUeU)
xxxx: DEC(app)