server :
  port : 8080
  servlet :
    session :
      cookie :
        http-only : true
        name : @project.artifactId@-sid
        path : /
        max-age : 3600
  tomcat :
    accesslog :
      enabled : true
      directory : /log
  jetty :
    accesslog :
      enabled : true
  undertow :
    accesslog :
      enabled : true
logging :
  level :
    p6spy : info
  file :
    name : @project.artifactId@
    path : ./log
sentry :
  dsn : http://c6715a73355a45ec948d9e0e668c0233@10.168.2.142:9000/2
  sentry-client-name : @project.artifactId@
spring :
  pid :
    file : @project.artifactId@-${server.port:8080}.pid
    fail-on-write-error : true

  application :
    name : @project.artifactId@
  autoconfigure :
    exclude : org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration,com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
  datasource :
    druid :
      #      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://10.168.2.142:3306/app?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name : com.p6spy.engine.spy.P6SpyDriver
      url : jdbc:p6spy:mysql://127.0.0.1:3306/app?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
      username : ENC(W/weR/Um/pwb9TnIi1IzDxVNGgcMX0wPqqDMC2WqE3WDuvJ6oAD04qlHsQCNuUeU)
      password : ENC(W/weR/Um/pwb9TnIi1IzDxVNGgcMX0wPqqDMC2WqE3WDuvJ6oAD04qlHsQCNuUeU)
      filter :
        slf4j :
          enabled : true
        stat :
          log-slow-sql : true
          slow-sql-millis : 200
          enabled : true
        wall :
          enabled : true
          db-type : mysql
      web-stat-filter :
        enabled : true
        exclusions : \*.js,\*.gif,\*.jpg,\*.png,\*.css,\*.ico,/druid/*
        url-pattern : /*
      stat-view-servlet :
#        当session 禁用时，不能配置用户密码
#        login-username : admin
#        login-password : admin
#        url-pattern : /druid/*
        enabled : true
      time-between-log-stats-millis : 300000
      test-while-idle : true
      validation-query : select 1
      max-active : 100
      min-idle : 10
  flyway :
    enabled : false
    url : ${spring.datasource.druid.url}
    password : ${spring.datasource.druid.password}
    user : ${spring.datasource.druid.username}
  session :
    store-type : hazelcast
    timeout : 3600
  cache :
    jcache :
      provider : com.hazelcast.cache.HazelcastCachingProvider
    type : hazelcast
  messages :
    basename : messages/message
#    cache-names :

jasypt :
  encryptor :
    password : 11112222
management :
  endpoint :
    httptrace :
      enabled : true
    shutdown :
      enabled : true
    metrics :
      enabled : true
    prometheus :
      enabled : true

# 图片校验码
validCodeImgUrl : /login/validateCode

core :
  hazelcast :
    appName : @project.artifactId@
    hazelcastIps :
      - 127.0.0.1
      - 127.0.0.1
